Profile updates with buttons and styling
molistreaming/app-swift-poc pull request #17
Opened 2022-01-17 17:09 UTC by denhihuynh

2022-01-18 12:27 UTC, Nojze requested changes
Snyggt jobbat! 😎 ❤️  Speedy gonzalez

2022-01-18 12:27 UTC, Nojze commented on Moli/Core/Screens/Profile/ProfileView.swift
> +                }.padding(.bottom, 40)
:art: Antog att du ville få effekten om att ha bilden pixel perfect, och det jag såg var att 40 är inte exakt det man vill ha, så jag testa det här och antar att det är värdet du vill ha istället
![simulator_screenshot_8D37AED1-DB62-4380-8C14-7185587DDCB9](https://user-images.githubusercontent.com/10032344/149933689-cf9c9e02-abf3-400a-934a-f922cd33ee80.png)

![simulator_screenshot_F387C3CF-881E-4156-8F47-EA958F424907](https://user-images.githubusercontent.com/10032344/149933741-c1911525-30f3-4dab-bb8c-c08f14adf025.png)

```suggestion
                }
                .padding(.bottom, profileImageSizeYOffset)
```

2022-01-18 12:27 UTC, Nojze commented on Moli/Core/Screens/Profile/ProfileView.swift
> +                VStack(alignment: .center, spacing: 16) {
:art: Här skulle det räcka med att förkorta eftersom by default så har en VStack alignment: .center, och spacing: 16
```suggestion
                VStack {
```

2022-01-18 12:27 UTC, Nojze commented on Moli/Core/Screens/Profile/ProfileView.swift
>                          if !biography.isEmpty {
:art: Legacy kod från min sida, här kan man istället skriva
```suggestion
                    if let biography = biography(),  !biography.isEmpty  {
```

2022-01-18 12:27 UTC, Nojze commented on Moli/Core/Screens/Profile/ProfileView.swift
> +                        if let websiteURL = websiteURL(), !websiteURL.isEmpty {
:art: Rent UI mässigt kommer det här beteende göra så att HStacken alltid finns som en element, vilket gör att Vstacken som wrappar den ger HStacken en effekt av padding på 16 pixlar, istället vill vi nog gömma hela Hstacken tills att det finns en websiteURL eller instagramLink

Så det du kan se i första bilden är beteendet som vi har nu, men i den andra så har jag testat gömma hstack:n om man inte har några sociala medier, och då finns det ingen extra padding

![simulator_screenshot_BB334559-B8D0-457F-9816-44DD8F2F6743](https://user-images.githubusercontent.com/10032344/149935011-8526ea28-754e-466c-9cc9-f64f257ef280.png)

![simulator_screenshot_6E8AC71B-16D9-4958-BC63-0384B36E4E2C](https://user-images.githubusercontent.com/10032344/149934866-8cd45d63-5a55-4ae9-ad6f-137863f5c312.png)

2022-01-18 12:27 UTC, Nojze commented on Moli/Core/Screens/Profile/ProfileView.swift
>                          HStack(spacing: 4) {
:art: Rent UX mässigt kommer det här beteendet ge `EditProfileView()` en paddingTrailing av 4px, även fast det är en EmptyView i sig själv så kommer den att räknas in som element, vilket i sin tur påverkar layout:en av knappen. I dey här fallet var det bara 4 extra pixlar, men det är mer som en hands up inför framtiden

```suggestion
                        HStack(spacing: 0) {
```

2022-01-18 12:27 UTC, Nojze commented on Moli/Core/Screens/Profile/ProfileView.swift
> +                            .frame(width: 140)
:art: Readability mässigt skulle jag föredragit att ha den här modifier:n efter .buttonStyle, så att man förstår att den först får alla attributer från SuperButtonStyle, och sen så sätter man width:n

2022-01-18 12:27 UTC, Nojze commented on Moli/Core/Screens/Profile/ProfileView.swift
>                          HStack(spacing: 4) {
Du kan testa det här genom att ha spacing: 40, så kommer du se vad jag menar

2022-01-18 12:27 UTC, Nojze commented on Moli/Core/Screens/UserLists/UserListView.swift
> +}
:art: Det finns `UserListType` längst ner i filen som också används i data modellerna av friends, following and followers, så jag skulle byta ut den mot den här `ListType`

2022-01-18 12:27 UTC, Nojze commented on Moli/Core/Screens/UserLists/UserListView.swift
> +
:art: För att slippa `default` case:t, så kan du ha en initial value istället 
```suggestion
    init(startingOn: ListType = .friends, user: UserAPI.UserResponse) {
        switch startingOn {
        case .friends:
            self.selectedTabIndex = 0
        case .following:
            self.selectedTabIndex = 2
        case .followers:
            self.selectedTabIndex = 1
        }
```

2022-01-18 12:27 UTC, Nojze commented on Moli/Core/Screens/UserLists/UserListsView.swift
> +}
❓ Verkar ha blviit något fel med fil referenserna tror jag, det här är en outdated fil
```suggestion
```

2022-01-18 15:06 UTC, denhihuynh commented on Moli/Core/Screens/Profile/FriendsAndFollowSection.swift
> +                    .frame(maxWidth: .infinity)
Det funkar inte, det blir inte samma resultat. Det kanske beror på att de ligger i en navigationlink under?

2022-01-18 15:09 UTC, denhihuynh commented on Moli/Core/Screens/Profile/FriendsAndFollowSection.swift
> +        .padding(.horizontal, 20)
Inget verkar det som. Jag tar bort

2022-01-18 15:10 UTC, denhihuynh commented on Moli/Core/Screens/Profile/FriendsAndFollowSection.swift
> +                    }
Yep, kan testa

2022-01-18 15:24 UTC, denhihuynh commented on Moli/Core/Screens/Profile/FriendsAndFollowSection.swift
> +struct FriendsAndFollowSection: View {
Bra input, jag ändrar.

2022-01-19 09:00 UTC, Nojze requested changes

2022-01-19 09:00 UTC, Nojze commented on Moli/Core/Screens/Profile/ProfileStatsView.swift
> +            if userInfo.friends != 0 {
❓ Vad är anledningen till att gömma friends när man har 0 vänner? Är det en design beslut?

2022-01-19 09:00 UTC, Nojze commented on Moli/Core/Screens/Profile/ProfileStatsView.swift
> +        HStack {
:art: Har insett att HStack:n inte ger spacing effekten till Dividers, testade koden fram och tillbaks, och kom fram med att slutresultatet ska se ut något som följande om den ska matcha design layout:n

 ```suggestion
    var statsDivider: some View {
        Divider()
        .padding(.horizontal)
    }

    var body: some View {
        HStack(spacing: 0) {
```

2022-01-19 09:00 UTC, Nojze commented on Moli/Core/Screens/Profile/FriendsAndFollowSection.swift
> +        .padding(.horizontal, 20)
:bomb: Men utifrån designen så ska inte varje stat ta 1/3 av skärmens bredd väl..? Har testat lokalt och fått det att funka genom att köra en .frame(maxWidth: .infinity) i själva HStacken

2022-01-19 09:00 UTC, Nojze commented on Moli/Core/Screens/Profile/FriendsAndFollowSection.swift
> +                            .foregroundColor(.primary)
Aha juste, det är pga att den wrappas av en NavigationLink som by default ger appens `accentColor`

2022-01-19 09:00 UTC, Nojze commented on Moli/Core/Screens/Profile/ProfileStatView.swift
> +        .frame(maxWidth: .infinity)
:art: Med åtanke på mina andra comments om maxWidth och HStack:n
```suggestion
```

2022-01-19 13:14 UTC, merged